### ISSUE TITLE
Script/Goal to convert existing cobertura.ser to converted-converage.xml

### ISSUE THREAD

**Issue by Ashwinsai** [QualInsight/qualinsight-mojo-cobertura#29]
What I'm planning to do is to run my selenium tests and try checking the functional test coverage in the integration test coverage block. Cobertura supports this . Please check http://www.mojohaus.org/cobertura-maven-plugin/instrumentingDeploymentArtifact.html

In this case, cobertura generates a datafile .ser file(as always) and it provides a script (bat/sh) to convert the .ser to .XML or .html files.

Since this plugin converts the coverage XML to converted-converage.xml (which has obvious differences in the XML schema) , I am not able to use this plugin for running my selenium scripts.

Is it possible to provide a script or any other way which can just convert any coverage.xml file (having cobertura XML schema) to converted-coverage.xml. 
This feature would complete the plugin's functionality relative to cobertura.

What I did was to follow the instructions in the link i mentioned above and run in maven "clean compile cobertura:cobertura" and then run the Selelnium tests and then flush the result to cobertura.ser. After that, I use in command line "cobertura-report.bat --format html --datafile C:\MyProject\build\cobertura.ser --destination C:\MyProject\reports\coverage C:\MyProject\src"
[ check https://github.com/cobertura/cobertura/wiki/Command-Line-Reference ] to generate the coverage.xml file. 

The problem I face is to I'm not able to convert it to converted-coverage.xml which basically has a different xml schema and hence does not reflect properly in Sonar. 

What I need is a route from cobertura.ser to converted-coverage.xml..

P.S. : Already starred !

**Comment by pawlakm** [comment]
Hi try to use the report-it-coverage goal. It takes an existing cobertura.ser and does all the job.

You have to make sure that when Maven post-integration-test phase starts:
- cobertura.ser is in '${project.basedir}' (this cannot be modified with 1.1.0) 
- instrumented classes are in target (or in directory specified by classesDirectoryPath)
- original classes are in cobertura/backup-classes (or in directory specified by backupClassesDirectoryPath)

And that:
- path to source files is correctly configured (see your last question #28)

Note that instead of using cobertura mojo, you could probably instrument your code with this plugin (it would probably simplify your configuration) prior to running your selenium tests.

Cheers

**Comment by pawlakm** [comment]
Starting with 2.0.0 `cobertura.ser` file location will be configurable in `pom.xml`(through the `dataFilePath`parameter).

**Comment by Ashwinsai** [comment]
Hi,

I ran with the qualinsight plugin & got the coverage results. There are few small issues which i will post on the other thread.

But what I'm trying to do is still giving me problems:

I shall list out the details of what I did:

**Things Done**:

Set the config as below for the plugin:

```
<configuration>
<classesDirectoryPath> target/classes </classesDirectoryPath>
<backupClassesDirectoryPath> target/generated-classes/cobertura </backupClassesDirectoryPath>
<baseDirectoryPath>src/java </baseDirectoryPath>
</configuration>
```

Path to source files is provided as well.

Ran cobertura:instrument and got the cobertura.ser file which i copied to the project base directory. 
Now, ran report-it-coverage goal. It gave me the below error.

**Question:**
    1. Is the cobertura.ser generated from cobertura plugin and the one from qualinsight plugin different?
    2. If thats the case, is it possible for the qualinsight plugin to allow for instrumentation of automation scripts?
1. Is it possible to bring the qualinsight generated .ser file same as cobertura plugin generated .ser file?

```
[DEBUG] Configuring mojo com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage from plugin realm ClassRealm[plugin>com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]
[DEBUG] Configuring mojo 'com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage' with basic configurator -->
[DEBUG]   (f) backupClassesDirectoryPath = target/generated-classes/cobertura
[DEBUG]   (f) baseDirectoryPath = src/java
[DEBUG]   (f) calculateMethodComplexity = false
[DEBUG]   (f) classesDirectoryPath = target/classes
[DEBUG]   (f) convertToSonarQubeOutput = true
[DEBUG]   (f) destinationDirectoryPath = C:\Users\AS80920\git\cov\communicator-ui\target/cobertura/it/
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) projectDirectoryPath = C:\Users\AS80920\git\cov\communicator-ui/
[DEBUG] -- end configuration --
[DEBUG] Preparing Cobertura report generation directories
[DEBUG] Building Cobertura report generation arguments
[DEBUG] Generating Cobertura report
[INFO] Cobertura: Loaded information on 130 classes.
[DEBUG] Cleaning up file system after Cobertura report generation
[DEBUG] Converting Cobertura report to SonarQube generic test coverage report format
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping XStreamCommunicator
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.892s
[INFO] Finished at: Sat Jun 25 18:35:03 IST 2016
[INFO] Final Memory: 17M/259M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage (default-cli) on project XStreamCommunicator: Execution default-cli of goal com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage failed: String index out of range: -33 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage (default-cli) on project XStreamCommunicator: Execution default-cli of goal com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage failed: String index out of range: -33
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.qualinsight.mojo.cobertura:qualinsight-mojo-cobertura-core:1.1.0:report-it-coverage failed: String index out of range: -33
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -33
    at java.lang.String.substring(String.java:1931)
    at com.qualinsight.mojo.cobertura.core.AbstractReportMojo.convertReport(AbstractReportMojo.java:103)
    at com.qualinsight.mojo.cobertura.core.AbstractReportMojo.convertToSonarQubeReport(AbstractReportMojo.java:90)
    at com.qualinsight.mojo.cobertura.core.AbstractCleaningReportMojo.execute(AbstractCleaningReportMojo.java:54)
    at com.qualinsight.mojo.cobertura.core.ITCoverageReportMojo.execute(ITCoverageReportMojo.java:31)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    ... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by pawlakm** [comment]
Hi,

> 1. Is the cobertura.ser generated from cobertura plugin and the one from qualinsight plugin different?

It shouldn't if you use the same version of cobertura (my plugin uses version 2.1.1, what version did you use ?)

> 1. If thats the case, is it possible for the qualinsight plugin to allow for instrumentation of automation scripts?

What do you mean by "automation scripts?" Are you talking about IT tests run against a deployed version of your application ? If that's the case you can already do it. The example shows how to do it with Jetty, but it shouldn't be difficult to do it with Tomcat.

**Comment by pawlakm** [comment]
Your `baseDirectoryPath` is incorrect. It must be an absolute path, not a relative one. it should start with `${project.basedir}/`

**Comment by Ashwinsai** [comment]
Hi,

I use cobertura maven plugin version 2.7 and as per their site data (http://www.mojohaus.org/cobertura-maven-plugin/), it uses version 2.1.1.  [This plugin uses Cobertura version 2.1.1 and requires Java 1.6.
]

If time permits, can you please try a sample run where you maven run "clean cobertura:cobertura" and get the cobertura.ser and use that file to run the it/ut report goal of qualinsight?? 

My  pom config is mentioned in my final comment in the issue page https://github.com/QualInsight/qualinsight-mojo-cobertura/issues/28

I am pasting the main part of the pom just for reference:

```
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>cobertura-maven-plugin</artifactId>
    <version>2.7</version>
    <configuration>
        <formats>
            <format>html</format>
            <format>xml</format>
        </formats>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>5.0.3</version>
        </dependency>
    </dependencies>
</plugin>
```

Would be great if you could try it out and see for yourself.

**Comment by pawlakm** [comment]
It would be great if you could provide a sample simple project that illustrates your issue.
