### ISSUE TITLE
Missing sources tag in generated coverage.xml file

### ISSUE THREAD

**Issue by jakob-o** [QualInsight/qualinsight-mojo-cobertura#33]
Hi,
thank you very much for providing this plugin. Unfortunately Jenkins is unable to find some of the source files. When I checked the coverage.xml files the <sources>-tag is empty. Diving a little bit into cobertura and report generation I suspect a missing call to [ArgumentsBuilder.addSources ](https://github.com/cobertura/cobertura/blob/db3bedf3334d8f35bad7ca3c6f4d777be6a09fc5/cobertura/src/main/java/net/sourceforge/cobertura/dsl/ArgumentsBuilder.java#L237). However I am not sure if this is the cause of the problem. I might give it some additional checking an provide a PR if this is the case.

Regards

Jakob

**Comment by pawlakm** [comment]
Hi,

Did you try version 2.0.0 and used the ``sourcesPath`` option ? (Yes it is not released yet... my bad)

If you're using a non standard directory layout, check the companion example project. The `[nonstandard](https://github.com/QualInsight/qualinsight-mojo-cobertura-example/tree/master/nonstandard)` module shows how to configure the plugin if you're using a non-standard directory layout.

Michel

**Comment by jakob-o** [comment]
Hi, please see PR #37 for a fix

**Comment by pawlakm** [comment]
Hi again, I released a release candidate: 2.0.0-RC1 including 2.0.0 modifications as well as your PRs. Could you please check it ? Thanks in advance.

**Comment by jakob-o** [comment]
Looks good to me!
